//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PiStoreManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public string BID { get; set; }
        public string OID { get; set; }
        public string CID { get; set; }
        public string EID { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public Nullable<decimal> BTotalPrice { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Porder Porder { get; set; }
    }
}
